language: cpp
sudo: required
dist: xenial
compiler:
  - gcc
os:
  - linux
before_install:
  - sudo apt-get install -y liblapack-dev clang-6.0 build-essential cmake
                            libarmadillo-dev libboost-all-dev libopenmpi-dev
script:
  - cd $TRAVIS_BUILD_DIR && mkdir build_mpi && cd build_mpi && cmake -DMPI_BUILD=ON .. && make
  - cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake .. && make
after_success:
notifications:
  email: true
