language: cpp
sudo: required
dist: xenial
compiler:
  - gcc
os:
  - linux
before_install:
  - sudo apt-get install -y liblapack-dev clang build-essential openm
                            libarmadillo-dev libboost-all-dev cmake libopenmpi-dev
script:
  - cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake .. && make
  - cd $TRAVIS_BUILD_DIR && mkdir build_clang && cd build_clang && cmake -DCLANG_CXX=ON .. && make
after_success:
branches:
  only:
    - master
notifications:
  email: true
