language: cpp
sudo: required
dist: xenial
compiler:
  - gcc
os:
  - linux
before_install:
  - sudo apt-get install -y liblapack-dev clang-6.0 build-essential cmake
                            libarmadillo-dev libboost-all-dev libopenmpi-dev
script:
  - cd $TRAVIS_BUILD_DIR && bash travis_test.sh
after_success:
branches:
  only:
    - master
notifications:
  email: true
